name: prueba_tecnica
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  flutter_svg: ^1.0.1
  intl: ^0.18.1
  excel: ^3.0.0
  path_provider: ^2.1.0
  open_filex: ^4.3.4
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/background1.jpg
    - assets/background2.jpg
    - assets/logo.png
    - assets/google.png
    - assets/apple.svg
    - assets/alert.svg
    - assets/success.png
  fonts:
   - family: ProductSans
     fonts:
      - asset: assets/fonts/Product Sans Bold Italic.ttf
      - asset: assets/fonts/Product Sans Bold.ttf
      - asset: assets/fonts/Product Sans Italic.ttf
      - asset: assets/fonts/Product Sans Regular.ttf
